language: java
sudo: false # faster builds
before_script: cd xe-parent
script: 
- mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true
- mvn heroku:deploy-war -DskipTests=true -Dmaven.javadoc.skip=true


